.de BL
.IP \(bu 2
..
.TL
The Path To Linux
[ Volume 1 ]
.AU
Ace120C
.SH
Table of Content:
.IP "1." 3
.B Introduction
.BL 
What this book is?
.BL
Who it's for?
.BL
How to Use it
.BL
Installing Linux
.B 
.IP "2." 3
.B "What is Linux"
.BL
History
.BL
The Linux Kernel
.BL
Distributions
.IP "3." 3
.B "The Terminal"
.BL
Why the Terminal Exists
.BL
The Shell
.BL 
Terminal Emulators
.IP "4." 3
.B Navigation
.BL
Where am I? (pwd)
.BL
Looking Around (ls)
.BL
Changing Directories (cd)
